❯ python fixpoint-2.py testdata.txt 4  
---サーバ「10.20.30.1/15」の状況---
 -故障...「なし」
---サーバ「10.20.30.2/15」の状況---
 -故障...「なし」
---サーバ「10.20.30.3/15」の状況---
 -故障...「なし」
---サーバ「10.20.30.4/15」の状況---
 -故障...「なし」
---サーバ「10.20.30.5/15」の状況---
 -故障...「発生」1回発生しています。
   1回目:故障期間は「2020年12月31日20時00分00秒~2020年12月31日20時20分00秒」です。
---サーバ「10.20.30.6/15」の状況---
 -故障...「発生」1回発生しています。
   1回目:故障期間は「2020年12月31日20時00分00秒~2021年02月05日12時16分23秒」です。
---サーバ「10.20.30.7/15」の状況---
 -故障...「なし」
---サーバ「10.20.30.8/15」の状況---
 -故障...「発生」1回発生しています。
   1回目:故障期間は「2020年12月31日20時35分00秒~2020年12月31日20時55分00秒」です。
---サーバ「10.20.30.9/15」の状況---
 -故障...「発生」2回発生しています。
   1回目:故障期間は「2020年12月31日20時00分00秒~2020年12月31日20時20分00秒」です。
   2回目:故障期間は「2020年12月31日20時35分00秒~2020年12月31日20時55分00秒」です。

